/* ============================================
   DORENTME - DỮ LIỆU SẢN PHẨM (nguồn dữ liệu duy nhất)
   Dùng chung cho shop.html, chatbotAI.html, và mọi trang
   cần tra cứu sản phẩm theo tên/ảnh/giá.
   Nhúng: <script src="products.js"></script>
   ============================================ */
const shopProducts = [
    // ── Áo dài ──
    { name: 'FLANE – UYỂN KHANH',       image: 'image/ao_dai/flane_uyenkhanh.jpg',        category: 'ao-dai', categoryLabel: 'Áo dài',      brand: 'FLANE',          price3day: '300.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '260.000 vnd', priceTag: '1.900.000 vnd', priceDeposit: '1.200.000 vnd', rating: 4.8, reviews: 42,  likes: 87 },
    { name: 'LINN DESIGN – TUỆ HIỀN',   image: 'image/ao_dai/linn_design_tue_hien.jpg',   category: 'ao-dai', categoryLabel: 'Áo dài',      brand: 'Khác',           price3day: '340.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '295.000 vnd', priceTag: '1.590.000 vnd', priceDeposit: '1.200.000 vnd', rating: 4.9, reviews: 38,  likes: 74 },
    { name: 'MAINICHI – MỘC MIÊN',      image: 'image/ao_dai/mainichi_moc_mien.png',      category: 'ao-dai', categoryLabel: 'Áo dài',      brand: 'Mainichi',       price3day: '260.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '220.000 vnd', priceTag: '1.200.000 vnd', priceDeposit: '800.000 vnd',   rating: 4.7, reviews: 31,  likes: 65 },
    { name: 'MAINICHI – YÊN CHI',       image: 'image/ao_dai/mainichi_yen_chi.jpg',       category: 'ao-dai', categoryLabel: 'Áo dài',      brand: 'Mainichi',       price3day: '290.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '250.000 vnd', priceTag: '1.550.000 vnd', priceDeposit: '900.000 vnd',   rating: 4.8, reviews: 55,  likes: 102 },
    { name: 'MAISON LONG – NIỀM NỖI',   image: 'image/ao_dai/maison_long_niem_no.jpg',    category: 'ao-dai', categoryLabel: 'Áo dài',      brand: 'MAISON LONG',    price3day: '220.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '180.000 vnd', priceTag: '1.150.000 vnd', priceDeposit: '700.000 vnd',   rating: 4.6, reviews: 28,  likes: 59 },
    { name: 'D.CHIC NÀNG THƠ PHỐ HỘI',  image: 'image/ao_dai/dchic-nang-tho-pho-hoi.jpg', category: 'ao-dai', categoryLabel: 'Áo dài',      brand: 'D.CHIC',         price3day: '320.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '280.000 vnd', priceTag: '1.950.000 vnd', priceDeposit: '1.200.000 vnd', rating: 4.9, reviews: 67,  likes: 134 },
    { name: 'D.CHIC COUTURE',            image: 'image/ao_dai/dchic_couture.jpg',           category: 'ao-dai', categoryLabel: 'Áo dài',      brand: 'D.CHIC',         price3day: '500.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '450.000 vnd', priceTag: '3.500.000 vnd', priceDeposit: '2.000.000 vnd', rating: 5.0, reviews: 89,  likes: 178 },
    { name: 'D.CHIC XUÂN VIÊN',          image: 'image/ao_dai/d.chic_xuan_vien.jpg',        category: 'ao-dai', categoryLabel: 'Áo dài',      brand: 'D.CHIC',         price3day: '480.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '440.000 vnd', priceTag: '2.850.000 vnd', priceDeposit: '2.000.000 vnd', rating: 4.9, reviews: 73,  likes: 156 },
    { name: 'D.CHIC Ý NHIÊN',            image: 'image/ao_dai/dchic_y_nhien.jpg',           category: 'ao-dai', categoryLabel: 'Áo dài',      brand: 'D.CHIC',         price3day: '490.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '450.000 vnd', priceTag: '2.950.000 vnd', priceDeposit: '2.000.000 vnd', rating: 4.8, reviews: 61,  likes: 120 },
    { name: 'D.CHIC THIÊN Ý',            image: 'image/ao_dai/d_chic_thien_y.jpg',          category: 'ao-dai', categoryLabel: 'Áo dài',      brand: 'D.CHIC',         price3day: '450.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '410.000 vnd', priceTag: '2.600.000 vnd', priceDeposit: '1.900.000 vnd', rating: 4.7, reviews: 44,  likes: 93 },
    // ── Váy đi biển ──
    { name: 'TIPBLU – ĐẦM VOAN TÍM LAVENDER',          image: 'image/vay_di_bien/tipblu_dam_voan_tim_lavender.jpg',       category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'Khác',        price3day: '190.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '160.000 vnd', priceTag: '930.000 vnd',   priceDeposit: '650.000 vnd', rating: 4.7, reviews: 38, likes: 76 },
    { name: 'CHOUCHOU – ĐẦM REN NUDE DÁNG DÀI',        image: 'image/vay_di_bien/chou_chou_dam_ren_nude_dang_dai.jpg',    category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'CHOUCHOU',    price3day: '255.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '225.000 vnd', priceTag: '1.110.000 vnd', priceDeposit: '800.000 vnd', rating: 4.8, reviews: 51, likes: 95 },
    { name: 'AMELIE – VANESSA DRESS XANH NHẠT',         image: 'image/vay_di_bien/amelie_vanessa_dress_xanh_nhat.jpg',     category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'AMELIEE',     price3day: '290.000 vnd', priceExtra: '(Trên 3 ngày +40.000 vnd/ngày)', price1day: '250.000 vnd', priceTag: '1.530.000 vnd', priceDeposit: '900.000 vnd', rating: 4.9, reviews: 64, likes: 118 },
    { name: 'JOLIE LOFT – VÁY LƯỚI MOLLY DRESS NÂU',   image: 'image/vay_di_bien/jolie_loft_vay_luoi_molly_dress_nau.jpg', category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'JOLIE LOFT',  price3day: '270.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '230.000 vnd', priceTag: '2.150.000 vnd', priceDeposit: '800.000 vnd', rating: 4.8, reviews: 47, likes: 89 },
    { name: 'FLANE – REN CỔ YẾM',                       image: 'image/vay_di_bien/flane_ren_co_yem.jpg',                   category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'FLANE',       price3day: '240.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '200.000 vnd', priceTag: '1.080.000 vnd', priceDeposit: '800.000 vnd', rating: 4.7, reviews: 33, likes: 67 },
    { name: 'JOLIE LOFT – LỤA',                          image: 'image/vay_di_bien/jolie_loft_lua.jpg',                     category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'JOLIE LOFT',  price3day: '195.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '165.000 vnd', priceTag: '1.320.000 vnd', priceDeposit: '700.000 vnd', rating: 4.8, reviews: 55, likes: 102 },
    { name: 'JOLIE LOFT – VÁY REN CÓ TAY',              image: 'image/vay_di_bien/jolie_loft_vay_ren_co_tay.jpg',          category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'JOLIE LOFT',  price3day: '220.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '190.000 vnd', priceTag: '1.812.000 vnd', priceDeposit: '700.000 vnd', rating: 4.6, reviews: 29, likes: 58 },
    { name: 'FLANE – REN BỒ MÙI TRẺ VAI',               image: 'image/vay_di_bien/flane_ren_bo_mui_tre_vai.jpg',           category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'FLANE',       price3day: '195.000 vnd', priceExtra: '(Trên 3 ngày +40.000 vnd/ngày)', price1day: '165.000 vnd', priceTag: '1.006.500 vnd', priceDeposit: '700.000 vnd', rating: 4.7, reviews: 41, likes: 83 },
    { name: 'AMELIE – VÁY BÍ BABYDOLL CỔ YẾM',          image: 'image/vay_di_bien/amelie_vay_bi_babydoll_co_yem.jpg',      category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'AMELIEE',     price3day: '170.000 vnd', priceExtra: '(Trên 3 ngày +40.000 vnd/ngày)', price1day: '140.000 vnd', priceTag: '870.000 vnd',   priceDeposit: '600.000 vnd', rating: 4.6, reviews: 26, likes: 54 },
    { name: 'VÁY REN PHỐI TƠ',                           image: 'image/vay_di_bien/vay_ren_phoi_to.jpg',                    category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'Khác',        price3day: '130.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '100.000 vnd', priceTag: '680.000 vnd',   priceDeposit: '400.000 vnd', rating: 4.5, reviews: 19, likes: 43 },
    { name: 'AMELIEE – GARMENT',                          image: 'image/vay_di_bien/ameliee_garment.jpg',                    category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'AMELIEE',     price3day: '175.000 vnd', priceExtra: '(Trên 3 ngày +40.000 vnd/ngày)', price1day: '140.000 vnd', priceTag: '888.000 vnd',   priceDeposit: '700.000 vnd', rating: 4.7, reviews: 35, likes: 71 },
    { name: 'AMELIEE – DIVA',                             image: 'image/vay_di_bien/ameliee_diva.webp',                      category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'AMELIEE',     price3day: '190.000 vnd', priceExtra: '(Trên 3 ngày +40.000 vnd/ngày)', price1day: '150.000 vnd', priceTag: '960.000 vnd',   priceDeposit: '700.000 vnd', rating: 4.8, reviews: 48, likes: 92 },
    { name: 'MAISON LONG – THỦY MỊ',                     image: 'image/vay_di_bien/maison_long_thuy_mi.jpg',                category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'MAISON LONG', price3day: '230.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '190.000 vnd', priceTag: '1.250.000 vnd', priceDeposit: '750.000 vnd', rating: 4.9, reviews: 57, likes: 109 },
    { name: 'VÁY HOA MÙA HÈ',                            image: 'image/vay_di_bien/vay_hoa_mua_he.jpg',                     category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'Khác',        price3day: '120.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '90.000 vnd',  priceTag: '594.000 vnd',   priceDeposit: '300.000 vnd', rating: 4.5, reviews: 22, likes: 47 },
    { name: 'SET VÁY 2 DÂY + CHÂN VÁY TRẮNG KEM LANNIE', image: 'image/vay_di_bien/set_vay_2_day_chan_vay_trang_kem_lannie.jpg', category: 'vay-di-bien', categoryLabel: 'Váy đi biển', brand: 'Khác', price3day: '120.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '100.000 vnd', priceTag: '650.000 vnd', priceDeposit: '400.000 vnd', rating: 4.6, reviews: 31, likes: 63 },
    // ── Váy dự tiệc ──
    { name: 'SÒ VINTAGE – NATHALIA',                image: 'image/vay_du_tiec/so_vintage_nathalia.jpg',                category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'SÒ VINTAGE',     price3day: '560.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '490.000 vnd', priceTag: '3.620.000 vnd', priceDeposit: '2.000.000 vnd', rating: 5.0, reviews: 120, likes: 203 },
    { name: 'TIPBLU – ĐẦM VOAN TÍM LAVENDER',       image: 'image/vay_du_tiec/tipblu_dam_voan_tim_lavender.jpg',       category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'Khác',           price3day: '190.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '160.000 vnd', priceTag: '930.000 vnd',   priceDeposit: '650.000 vnd',   rating: 4.7, reviews: 38,  likes: 76 },
    { name: 'JOLIE LOFT – ĐẦM LỤA KEM HALI DRESS',  image: 'image/vay_du_tiec/jolie_loft_dam_lua_kem_hali_dress.jpg',  category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'JOLIE LOFT',     price3day: '200.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '175.000 vnd', priceTag: '1.600.000 vnd', priceDeposit: '600.000 vnd',   rating: 4.9, reviews: 86,  likes: 128 },
    { name: 'CHOUCHOU – ĐẦM REN NUDE DÁNG DÀI',     image: 'image/vay_du_tiec/chouchou_dam_ren_nude_dang_dai.jpg',     category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'CHOUCHOU',       price3day: '255.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '225.000 vnd', priceTag: '1.110.000 vnd', priceDeposit: '800.000 vnd',   rating: 4.8, reviews: 51,  likes: 95 },
    { name: 'AMELIE – VANESSA DRESS XANH NHẠT',      image: 'image/vay_du_tiec/amelie_vanessa_dress_xanh_nhat.jpg',     category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'AMELIEE',        price3day: '290.000 vnd', priceExtra: '(Trên 3 ngày +40.000 vnd/ngày)', price1day: '250.000 vnd', priceTag: '1.530.000 vnd', priceDeposit: '900.000 vnd',   rating: 4.9, reviews: 64,  likes: 118 },
    { name: 'JOLIE LOFT – VÁY LƯỚI MOLLY DRESS NÂU', image: 'image/vay_du_tiec/jolie_loft_vay_luoi_molly_dress_nau.jpg', category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'JOLIE LOFT',   price3day: '270.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '230.000 vnd', priceTag: '2.150.000 vnd', priceDeposit: '800.000 vnd',   rating: 4.8, reviews: 47,  likes: 89 },
    { name: 'SÒ VINTAGE – LYRA',                     image: 'image/vay_du_tiec/so_vintage_lyra.jpg',                    category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'SÒ VINTAGE',     price3day: '420.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '388.000 vnd', priceTag: '2.388.000 vnd', priceDeposit: '1.500.000 vnd', rating: 4.8, reviews: 59,  likes: 113 },
    { name: 'WONDER HOUSE – LUA DRESS KEM',          image: 'image/vay_du_tiec/wonder_house_lua_dress_kem.jpg',          category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'Khác',           price3day: '190.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '165.000 vnd', priceTag: '795.000 vnd',   priceDeposit: '500.000 vnd',   rating: 4.6, reviews: 33,  likes: 67 },
    { name: 'SÒ VINTAGE – VELIA (ĐEN)',              image: 'image/vay_du_tiec/so_vintage_velia(den).jpg',              category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'SÒ VINTAGE',     price3day: '440.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '390.000 vnd', priceTag: '2.590.000 vnd', priceDeposit: '1.500.000 vnd', rating: 4.9, reviews: 71,  likes: 139 },
    { name: 'SÒ VINTAGE – VELIANA (ĐEN)',            image: 'image/vay_du_tiec/so_vintage_veliana(den).jpg',            category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'SÒ VINTAGE',     price3day: '340.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '290.000 vnd', priceTag: '1.969.000 vnd', priceDeposit: '1.300.000 vnd', rating: 4.7, reviews: 44,  likes: 88 },
    { name: 'CHOUCHOU – ĐẦM DÀI REN CHOÀNG',        image: 'image/vay_du_tiec/chouchou_dam_dai_ren_choang.jpg',         category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'CHOUCHOU',       price3day: '230.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '200.000 vnd', priceTag: '990.000 vnd',   priceDeposit: '700.000 vnd',   rating: 4.7, reviews: 36,  likes: 72 },
    { name: 'SÒ VINTAGE – VELIA',                    image: 'image/vay_du_tiec/so_vintage_velia.jpg',                   category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'SÒ VINTAGE',     price3day: '440.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '390.000 vnd', priceTag: '2.590.000 vnd', priceDeposit: '1.500.000 vnd', rating: 4.9, reviews: 68,  likes: 132 },
    { name: 'SÒ VINTAGE – LAFINE',                   image: 'image/vay_du_tiec/so_vintage_lafine.jpg',                  category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'SÒ VINTAGE',     price3day: '450.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '400.000 vnd', priceTag: '2.629.000 vnd', priceDeposit: '1.500.000 vnd', rating: 4.8, reviews: 55,  likes: 107 },
    { name: 'SÒ VINTAGE – VELIANA',                  image: 'image/vay_du_tiec/so_vintage_veliana.png',                 category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'SÒ VINTAGE',     price3day: '340.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '290.000 vnd', priceTag: '1.969.000 vnd', priceDeposit: '1.300.000 vnd', rating: 4.7, reviews: 41,  likes: 82 },
    { name: 'JOLIE LOFT – VÁY LỤA LUALA DRESS',     image: 'image/vay_du_tiec/jolie_loft_vay_lua_luala_dress.png',     category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'JOLIE LOFT',     price3day: '240.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '210.000 vnd', priceTag: '1.890.000 vnd', priceDeposit: '800.000 vnd',   rating: 4.8, reviews: 62,  likes: 119 },
    { name: 'HƯƠNG BOUTIQUE – LOUISE LACE DRESS',    image: 'image/vay_du_tiec/huong_boutique_louise_lace_dress.jpg',   category: 'vay-du-tiec', categoryLabel: 'Váy dự tiệc', brand: 'HƯƠNG BOUTIQUE', price3day: '420.000 vnd', priceExtra: '(Trên 3 ngày +50.000 vnd/ngày)', price1day: '380.000 vnd', priceTag: '2.050.000 vnd', priceDeposit: '1.400.000 vnd', rating: 4.9, reviews: 77,  likes: 145 },
    // ── Phụ kiện ──
    { name: 'TÚI NHUNG ĐEN D.CHIC',                                      image: 'image/phu_kien/tui_nhung_den_dchic.jpg',       category: 'phu-kien', categoryLabel: 'Phụ kiện', brand: 'D.CHIC',  price3day: '80.000 vnd',  priceExtra: '(Trên 3 ngày +20.000 vnd/ngày)', price1day: '60.000 vnd',  priceTag: '980.000 vnd',  priceDeposit: '300.000 vnd', rating: 4.7, reviews: 28, likes: 54 },
    { name: 'TÚI DA ĐEN MYS.P',                                           image: 'image/phu_kien/tui_da_den_mysp.jpg',           category: 'phu-kien', categoryLabel: 'Phụ kiện', brand: 'Mys.P',   price3day: '90.000 vnd',  priceExtra: '(Trên 3 ngày +20.000 vnd/ngày)', price1day: '70.000 vnd',  priceTag: '590.000 vnd',  priceDeposit: '400.000 vnd', rating: 4.6, reviews: 19, likes: 41 },
    { name: 'TÚI DA ĐỎ',                                                  image: 'image/phu_kien/tui_da_do.jpg',                 category: 'phu-kien', categoryLabel: 'Phụ kiện', brand: 'Khác',    price3day: '70.000 vnd',  priceExtra: '(Trên 3 ngày +10.000 vnd/ngày)', price1day: '50.000 vnd',  priceTag: '',             priceDeposit: '300.000 vnd', rating: 4.5, reviews: 14, likes: 29 },
    { name: 'TÚI TRỨNG NGỌC TRAI',                                        image: 'image/phu_kien/tui_trung_ngoc_trai.jpg',       category: 'phu-kien', categoryLabel: 'Phụ kiện', brand: 'Khác',    price3day: '120.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '100.000 vnd', priceTag: '',             priceDeposit: '400.000 vnd', rating: 4.8, reviews: 33, likes: 67 },
    { name: 'COMBO PHỤ KIỆN ÁO DÀI (VÒNG + BỜM + TÚI)',                  image: 'image/phu_kien/com_bo_phu_kien_ao_dai.jpg',    category: 'phu-kien', categoryLabel: 'Phụ kiện', brand: 'CHIRON',  price3day: '100.000 vnd', priceExtra: '(Trên 3 ngày +20.000 vnd/ngày)', price1day: '80.000 vnd',  priceTag: '',             priceDeposit: '300.000 vnd', rating: 4.8, reviews: 41, likes: 78 },
    { name: 'COMBO NGỌC TRAI (TÚI + VÒNG CỔ, TÚI + BỜM/VÒNG TAY)',      image: 'image/phu_kien/combo_ngoc_trai.jpg',           category: 'phu-kien', categoryLabel: 'Phụ kiện', brand: 'CHIRON',  price3day: '100.000 vnd', priceExtra: '(Trên 3 ngày +20.000 vnd/ngày)', price1day: '80.000 vnd',  priceTag: '',             priceDeposit: '300.000 vnd', rating: 4.7, reviews: 36, likes: 71 },
    { name: 'TÚI MŨ ĐI BIỂN',                                             image: 'image/phu_kien/tui_mu_di_bien.jpg',            category: 'phu-kien', categoryLabel: 'Phụ kiện', brand: 'Khác',    price3day: '100.000 vnd', priceExtra: '(Trên 3 ngày +20.000 vnd/ngày)', price1day: '80.000 vnd',  priceTag: '500.000 vnd',  priceDeposit: '400.000 vnd', rating: 4.6, reviews: 22, likes: 46 },
    // ── Váy lụa ──
    { name: 'JOLIE LOFT – ĐẦM LỤA KEM HALI DRESS', image: 'image/vay_lua/jolie_loft_dam_lua_kem_hali_dress.jpg', category: 'vay-lua', categoryLabel: 'Váy lụa', brand: 'JOLIE LOFT', price3day: '200.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '175.000 vnd', priceTag: '1.600.000 vnd', priceDeposit: '600.000 vnd', rating: 4.9, reviews: 86, likes: 128 },
    { name: 'WONDER HOUSE – LUA DRESS KEM',          image: 'image/vay_lua/wonder_house_lua_dress_kem.jpg',        category: 'vay-lua', categoryLabel: 'Váy lụa', brand: 'Khác',       price3day: '190.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '165.000 vnd', priceTag: '795.000 vnd',   priceDeposit: '500.000 vnd', rating: 4.6, reviews: 33, likes: 67 },
    { name: 'JOLIE LOFT – VÁY LỤA LUALA DRESS',     image: 'image/vay_lua/jolie_loft_vaylua_dress.png',           category: 'vay-lua', categoryLabel: 'Váy lụa', brand: 'JOLIE LOFT', price3day: '240.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '210.000 vnd', priceTag: '1.890.000 vnd', priceDeposit: '800.000 vnd', rating: 4.8, reviews: 62, likes: 119 },
    { name: 'JOLIE LOFT – LỤA',                      image: 'image/vay_lua/jolie_loft_lua.jpg',                    category: 'vay-lua', categoryLabel: 'Váy lụa', brand: 'JOLIE LOFT', price3day: '195.000 vnd', priceExtra: '(Trên 3 ngày +30.000 vnd/ngày)', price1day: '165.000 vnd', priceTag: '1.320.000 vnd', priceDeposit: '700.000 vnd', rating: 4.8, reviews: 55, likes: 102 }
];
